version: '3.5'


networks:
  backend_network:
    name: prisma_prod_test
    driver: bridge

services:
  rabbit_prisma:
    container_name: rabbit_prisma
    image: bitnami/rabbitmq:latest
    environment:
      - RABBITMQ_USERNAME=$RABBITMQ_USERNAME
      - RABBITMQ_PASSWORD=$RABBITMQ_PASSWORD
    ports:
    - "15672:15672"
    labels:
      NAME: "rabbitmq_prisma"
    volumes:
    - "./rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins"
    networks: 
      - backend_network
    expose:
      - 5672
  prisma_main:
    container_name: prisma_main
    image: prismagraphql/prisma-prod:1.34 # prisma-prod for RabbitMQ scalling
    environment:
      PRISMA_CONFIG: |
        port: 4466
        rabbitUri: amqp://$RABBITMQ_USERNAME:$RABBITMQ_PASSWORD@rabbit:5672
        databases:
          default:
            connector: mysql
            host: mysql
            port: 3306
            user: $MYSQL_USER
            password: $MYSQL_PASSWORD
    expose:
      - 4466
    links:
      - rabbit_prisma:rabbit
      - mysql:mysql
    networks: 
      - backend_network
  prisma_dev:
    container_name: prisma_dev
    image: prismagraphql/prisma:1.34
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: mysql
            host: mysql
            port: 3306
            user: $MYSQL_USER
            password: $MYSQL_PASSWORD
    ports:
      - 4466:4466
    networks: 
      - backend_network
  # mongo:
  #   container_name: prisma_db
  #   image: mongo:3.6
  #   # restart: always
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: prisma
  #     MONGO_INITDB_ROOT_PASSWORD: prisma
  #   ports:
  #     - '27017:27017'
  #   volumes:
  #     - mongoPrisma:/data/db  

  mysql:
    container_name: prisma_db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks: 
      - backend_network

# volumes:
#   mongoPrisma: # for windows can't volume bind path.